### ISSUE TITLE
Inplementação defeituosa de #maps

### ISSUE THREAD

**Issue by srvaz** [srvaz/Casa-do-Idoso#1]
O estilo deve ser implementado em um arquivo scss e importado em style.scss para que possa ser processado de maneira correta. @lula2018 

**Solução**: 

1. Crie um arquivo dentro do diretório styles chamado _maps.scss e dentro dele insira as seguites linhas:
https://github.com/srvaz/Casa-do-Idoso/blob/36934876550fef0c8d5764f430ce09e99a5a4146/app/dist/style.css#L286-L287
2. Após isso importe o arquivo dentro de style.scss da seguinte maneira `@import 'maps'`

**Comment by lula2018** [comment]
Corrigido meu caro
