### ISSUE TITLE
Implementação de "localidades" fora do padrão

### ISSUE THREAD

**Issue by srvaz** [srvaz/Casa-do-Idoso#2]
As seguintes linhas devem ser retiradas de index.html e inseridas dentro do arquivo localidades.html que fica dentro do diretório includes. @lula2018 
https://github.com/srvaz/Casa-do-Idoso/blob/4eeb775c43e689dd1658707af9e15b86d16f35e8/app/index.html#L28-L47

**Comment by lula2018** [comment]
Corrigido meu friend
