### ISSUE TITLE
Má utilização da tag <p>

### ISSUE THREAD

**Issue by srvaz** [srvaz/Casa-do-Idoso#4]
Ficaria melhor utilizar uma lista para definir os locais ja que a tag `<p>` é destinada para parágrafos.  :wink:
@lula2018 
https://github.com/srvaz/Casa-do-Idoso/blob/778b0e4450ebc65a0d56cf3ce5407c784b9415c9/app/includes/localidades.html#L14-L17

**Comment by lula2018** [comment]
mano, só funciona o espaçamento entre as <li> quando coloco no style.css msm, se tiver como fazer fora dele me fala como faz kkkkk

**Comment by srvaz** [comment]
@lula2018 cara acho que se você inserir no _obj.scss vai, mas... caso não de mesmo assim provavelmente é algum erro no sass que não deve estar instalado na maquina ai vai ter que ir no readme na pagina inicial do repositório e la tem toda a documentação pra você instalar o ruby e o sass pra você instalar direitinho  :ok_hand:.

**Comment by lula2018** [comment]
é isso ai meu chapa
