### ISSUE TITLE
Alinhamento dos endereços

### ISSUE THREAD

**Issue by lula2018** [srvaz/Casa-do-Idoso#5]
Como faço pra alinhar a lista dos endereços? quando coloco um `<br` sem fechar com o `>` ele fica alinhado certinho, mas quando não coloco ele fica mais pra frente ????

`<br`

    <ul>
      <li> Rua fulano de tal, N° 000 </li>
      <li> Rua fulano de tal, N° 000 </li>
      <li> Rua fulano de tal, N° 000 </li>
      <li> Rua fulano de tal, N° 000 </li>
   </ul>
`

**Comment by srvaz** [comment]
@lula2018, a tag `<br>` não é uma boa para ser utilizada neste caso...
Oque acontece com esse "desalinhamento" da lista é que na verdade a `<ul>` possuí uma propriedade chamada "padding" como padrão. Para o alinhamento funcionar é preciso definir com o valor 0, assim não tera nenhuma margem interna fezendo com que os itens (`<li>`) fiquem "desalinhados".
Outra questão foi a que o @GuilhermeSillva levantou hoje a respeito de que quando insere a lista o paragrafo da `<section>` de baixo sofre uma interferência que o desalinha. Isso acontece por conta de uma margem que ja vem por padrão também. Oque deve ser feito e tirar essa margem na parte inferior do elemento.

**Ex.:**
```css
ul {
    margin-bottom: 0;
    padding: 0;
}
```

**Comment by lula2018** [comment]
show de bola, quando crescer quero ser que nem vc
