### ISSUE TITLE
Fora do padrão

### ISSUE THREAD

**Issue by srvaz** [srvaz/Casa-do-Idoso#6]
Estas propriedades devem ser inseridas dentro do arquivo "_obj.scss" situado na pasta styles, para que o código seja gerado corretamente evitando bugs na execução do gulp.
https://github.com/srvaz/Casa-do-Idoso/blob/7ee1ba3eda90dda718eaaacde1cdb83c96375d2b/app/dist/style.css#L56-L57

**Comment by lula2018** [comment]
pronto meu camarada
